import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium

# 1. Page Configuration
st.set_page_config(
    page_title="National Housing Policy Radar",
    page_icon="🏠",
    layout="wide"
)

# 2. Load Data
@st.cache_data
def load_data():
    try:
        # Load the CSV generated by the radar_sweep.py script
        df = pd.read_csv('legislation_master.csv')
        
        # Ensure coordinates are numeric for mapping
        df['Lat'] = pd.to_numeric(df['Lat'], errors='coerce')
        df['Lon'] = pd.to_numeric(df['Lon'], errors='coerce')
        
        # Fill missing values for filters to prevent sorting errors
        df['Status'] = df['Status'].fillna('Unknown')
        df['Theme'] = df['Theme'].fillna('General Housing Policy')
        
        return df.dropna(subset=['Lat', 'Lon'])
    except FileNotFoundError:
        # Return empty dataframe with correct columns if file doesn't exist yet
        return pd.DataFrame(columns=[
            'State', 'Identifier', 'Theme', 'Summary', 
            'Status', 'Link', 'Lat', 'Lon', 'Source'
        ])

df = load_data()

# 3. Sidebar Search & Filters
st.sidebar.title("Search & Filters")
st.sidebar.markdown("Audit state-level housing and zoning reforms across the US.")

# Keyword Search
search_query = st.sidebar.text_input("Search Summary or Identifier", "")

# State Filter
all_states = sorted(df['State'].unique().tolist()) if not df.empty else []
selected_states = st.sidebar.multiselect("Select States", options=all_states, default=all_states)

# Theme Filter (Safely handled)
if not df.empty:
    all_themes = sorted(df['Theme'].unique().astype(str).tolist())
else:
    all_themes = []
selected_themes = st.sidebar.multiselect("Select Policy Themes", options=all_themes, default=all_themes)

# Status Filter (Safely handled)
if not df.empty:
    all_statuses = sorted(df['Status'].unique().astype(str).tolist())
else:
    all_statuses = []
selected_statuses = st.sidebar.multiselect("Select Bill Status", options=all_statuses, default=all_statuses)

# 4. Filter Logic Execution
filtered_df = df[
    (df['State'].isin(selected_states)) &
    (df['Status'].isin(selected_statuses)) &
    (df['Theme'].isin(selected_themes))
]

if search_query:
    filtered_df = filtered_df[
        filtered_df['Summary'].str.contains(search_query, case=False, na=False) |
        filtered_df['Identifier'].str.contains(search_query, case=False, na=False)
    ]

# 5. Main Dashboard View
st.title("🏠 Housing & Zoning Policy Radar")
st.markdown(f"Currently tracking **{len(filtered_df)}** relevant legislative items.")

# Key Performance Indicators
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Jurisdictions", len(filtered_df['State'].unique()))
with col2:
    st.metric("Total Bills", len(filtered_df))
with col3:
    if not filtered_df.empty:
        common_theme = filtered_df['Theme'].value_counts().idxmax()
    else:
        common_theme = "N/A"
    st.metric("Top Policy Theme", common_theme)

# 6. Map Section
st.subheader("Geospatial Overview")

def get_status_color(status):
    """Assigns colors based on legislative progress."""
    s = str(status).lower()
    if any(word in s for word in ['pass', 'sign', 'enact', 'enrolled', 'chapter']):
        return "#28a745" # Green (Success)
    if any(word in s for word in ['fail', 'die', 'dead', 'veto', 'withdraw', 'defeat']):
        return "#dc3545" # Red (Blocked)
    return "#3186cc" # Blue (Active/In Progress)

if not filtered_df.empty:
    # Initialize Folium Map centered on the US
    m = folium.Map(location=[39.8283, -98.5795], zoom_start=4, tiles="cartodbpositron")
    
    for _, row in filtered_df.iterrows():
        # Build popup HTML safely
        popup_content = [
            f"<div style='font-family: sans-serif; min-width: 200px;'>",
            f"<b>{row['Identifier']} ({row['State']})</b><br>",
            f"<span style='background: #eee; padding: 2px 5px; border-radius: 3px; font-size: 10px;'>{row['Theme']}</span><br>",
            f"<i style='color: #666;'>{row['Status']}</i><br><br>",
            f"<p style='font-size: 12px; line-height: 1.4;'>{row['Summary']}</p>",
            f"<a href='{row['Link']}' target='_blank' style='color: #3186cc; font-weight: bold;'>View Bill Details</a>",
            f"</div>"
        ]
        popup_html = "".join(popup_content)
        
        color = get_status_color(row['Status'])
        
        folium.CircleMarker(
            location=[row['Lat'], row['Lon']],
            radius=8,
            popup=folium.Popup(popup_html, max_width=300),
            tooltip=f"{row['State']}: {row['Identifier']}",
            color=color,
            fill=True,
            fill_color=color,
            fill_opacity=0.7
        ).add_to(m)
    
    st_folium(m, width=1400, height=550, returned_objects=[])
else:
    st.info("Adjust the filters in the sidebar to see national results.")

# 7. Data Table Section
st.subheader("Legislative Detail Table")
st.dataframe(
    filtered_df[['State', 'Identifier', 'Status', 'Theme', 'Summary', 'Link']],
    column_config={
        "Link": st.column_config.LinkColumn("LegiScan URL"),
        "Summary": st.column_config.TextColumn("Bill Title", width="large")
    },
    use_container_width=True,
    hide_index=True
)

st.markdown("---")
st.caption("Data is audited monthly via LegiScan API. Map markers represent the geographic center of the reporting state.")
